language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.2
  - 1.9.1

cache:
  directories:
    - priv/plts

jobs:
  include:
    - stage: lint
      elixir: 1.9.1
      script:
        - mix format --check-formatted
        - mix credo
    - stage: dialyzer
      elixir: 1.9.1
      script: MIX_ENV=dev travis_wait 20 mix dialyzer --plt
